DROP TABLE PHONEBOOK PURGE;

CREATE TABLE PHONEBOOK (
    "PHONEBOOK_ID" NUMBER GENERATED ALWAYS AS IDENTITY ( START WITH 1 CACHE 20 ) NOT NULL ENABLE,
    "FIRST_NAME"   VARCHAR2(40) NOT NULL,
    "LAST_NAME"    VARCHAR2(40) NOT NULL,
    "PHONE_NUMBER" VARCHAR2(12) NOT NULL,
    "CREATE_DATE"  TIMESTAMP DEFAULT SYSDATE,
    PRIMARY KEY ("PHONEBOOK_ID")
);
